version: '3.3'

networks:
  proxy:
    external: true

services:
  ui:
    image: haroldmei/ui:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ui.entrypoints=http'
      - 'traefik.http.routers.ui.rule=Host(`ui.hmei.me`)'
      - 'traefik.http.middlewares.ui-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.ui.middlewares=ui-https-redirect'
      - 'traefik.http.routers.ui-secure.entrypoints=https'
      - 'traefik.http.routers.ui-secure.rule=Host(`ui.hmei.me`)'
      - 'traefik.http.routers.ui-secure.tls=true'
      - 'traefik.http.routers.ui-secure.tls.certresolver=http'
      - 'traefik.http.routers.ui-secure.service=ui'
      - 'traefik.http.services.ui.loadbalancer.server.port=3000'
      - 'traefik.docker.network=proxy'

  backend:
    image: haroldmei/backend:latest
    hostname: backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.entrypoints=http'
      - 'traefik.http.routers.backend.rule=Host(`backend.hmei.me)'
      - 'traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.backend.middlewares=backend-https-redirect'
      - 'traefik.http.routers.backend-secure.entrypoints=https'
      - 'traefik.http.routers.backend-secure.rule=Host(`backend.hmei.me`)'
      - 'traefik.http.routers.backend-secure.tls=true'
      - 'traefik.http.routers.backend-secure.tls.certresolver=http'
      - 'traefik.http.routers.backend-secure.service=backend'
      - 'traefik.http.services.backend.loadbalancer.server.port=5000'
      - 'traefik.docker.network=proxy'

    #ports:
    #  - '5000:5000'

  mongo:
    image: mongo
    command: --serviceExecutor adaptive
    hostname: mongo

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.entrypoints=http'
      - 'traefik.http.routers.traefik.rule=Host(`hmei.me`)'
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=hmei:$$apr1$$2atJRFCy$$7TuFsJB1YmkDoE/Cg1wI31'
      - 'traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.traefik.middlewares=traefik-https-redirect'
      - 'traefik.http.routers.traefik-secure.entrypoints=https'
      - 'traefik.http.routers.traefik-secure.rule=Host(`hmei.me`)'
      - 'traefik.http.routers.traefik-secure.middlewares=traefik-auth'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.traefik-secure.tls.certresolver=http'
      - 'traefik.http.routers.traefik-secure.service=api@internal'
